import fs from 'node:fs'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))

// One Visual C++ Redistributable per Windows target architecture. The native
// ARM64 build (NVIDIA RTX Spark, Windows on Arm) loads `win_arm64` Python
// extension modules that need the ARM64 runtime; the x64 build needs the x64
// one (also when it runs under Prism emulation on an ARM64 machine). Both
// aka.ms links are Microsoft's permanent "latest supported" redirects.
const VC_REDIST = {
  x64: {
    file: 'vc_redist.x64.exe',
    url: 'https://aka.ms/vc14/vc_redist.x64.exe',
    define: 'VC_REDIST_X64_VERSION',
  },
  arm64: {
    file: 'vc_redist.arm64.exe',
    url: 'https://aka.ms/vc14/vc_redist.arm64.exe',
    define: 'VC_REDIST_ARM64_VERSION',
  },
}

// electron-builder's `Arch` enum: ia32 = 0, x64 = 1, armv7l = 2, arm64 = 3.
// ToDesktop's afterPack hook forwards the same `arch` value. Accept the
// string spelling too so a future hook that passes names keeps working.
const ARCH_ARM64 = 3

/** The Windows target architecture of this pack, as a VC_REDIST key. */
export function redistArchForPack(arch) {
  return arch === ARCH_ARM64 || arch === 'arm64' ? 'arm64' : 'x64'
}

// VS_FIXEDFILEINFO starts with dwSignature = 0xFEEF04BD followed by
// dwStrucVersion = 0x00010000 (LE). Matching both eliminates any chance of a
// false positive from the 4-byte signature appearing incidentally in code or
// data sections of the ~24 MB redist binary.
const VS_FIXEDFILEINFO_SIGNATURE = Buffer.from([0xbd, 0x04, 0xef, 0xfe, 0x00, 0x00, 0x01, 0x00])

/**
 * Read the FileVersion (a.b.c.d) from a Win32 PE executable by locating the
 * VS_FIXEDFILEINFO struct embedded in its version resource. Used to discover
 * the bundled vc_redist.<arch>.exe version on any host platform without
 * shelling out to Windows-only tools.
 */
export function readPeFileVersion(exePath) {
  const buf = fs.readFileSync(exePath)
  const sigOffset = buf.indexOf(VS_FIXEDFILEINFO_SIGNATURE)
  if (sigOffset === -1) {
    throw new Error(`VS_FIXEDFILEINFO signature not found in ${exePath}`)
  }
  // VS_FIXEDFILEINFO layout (after the 4-byte signature):
  //   DWORD dwStrucVersion       (offset +4)
  //   DWORD dwFileVersionMS      (offset +8)  high16 = major, low16 = minor
  //   DWORD dwFileVersionLS      (offset +12) high16 = build, low16 = revision
  const ms = buf.readUInt32LE(sigOffset + 8)
  const ls = buf.readUInt32LE(sigOffset + 12)
  return {
    major: (ms >>> 16) & 0xffff,
    minor: ms & 0xffff,
    build: (ls >>> 16) & 0xffff,
    revision: ls & 0xffff,
  }
}

/**
 * Write a small NSH header next to the redistributables that the NSIS
 * installer `!include`s to learn which version(s) it bundles: one
 * `VC_REDIST_<ARCH>_VERSION` define per vc_redist.<arch>.exe present in the
 * build resources dir. Lets the installer skip the multi-minute redist run
 * when an equal-or-newer version is already on the user's machine, and lets
 * `installer.nsh` refuse to compile an installer whose architecture has no
 * redist. Regenerated from the directory contents on every pack, so the
 * x64 and arm64 packs of one build accumulate rather than overwrite.
 */
export function writeVcRedistVersionInclude(buildResourcesDir) {
  const lines = ['; Auto-generated by scripts/afterPack.mjs from vc_redist.<arch>.exe — do not edit.']
  for (const { file, define } of Object.values(VC_REDIST)) {
    const redistPath = path.join(buildResourcesDir, file)
    if (!fs.existsSync(redistPath)) continue
    const v = readPeFileVersion(redistPath)
    lines.push(`!define ${define} "${v.major}.${v.minor}.${v.build}.${v.revision}"`)
  }
  if (lines.length === 1) {
    throw new Error(`no vc_redist.<arch>.exe found in ${buildResourcesDir}`)
  }
  const includePath = path.join(buildResourcesDir, 'vc_redist_version.nsh')
  fs.writeFileSync(includePath, lines.join('\n') + '\n')
  console.log(`afterPack: wrote ${includePath} (${lines.slice(1).join('; ')})`)
}

async function ensureVcRedist(context) {
  const buildResourcesDir = context.packager.buildResourcesDir
  const redist = VC_REDIST[redistArchForPack(context.arch)]
  const vcRedistPath = path.join(buildResourcesDir, redist.file)
  const vcRedistTempPath = `${vcRedistPath}.tmp`

  if (!fs.existsSync(vcRedistPath)) {
    console.log(`afterPack: downloading ${redist.url}`)
    const response = await fetch(redist.url)

    if (!response.ok || !response.body) {
      throw new Error(`Failed to download VC++ redistributable (${response.status} ${response.statusText})`)
    }

    fs.mkdirSync(buildResourcesDir, { recursive: true })
    await pipeline(Readable.fromWeb(response.body), fs.createWriteStream(vcRedistTempPath))
    fs.renameSync(vcRedistTempPath, vcRedistPath)
    console.log(`afterPack: saved ${vcRedistPath}`)
  }

  writeVcRedistVersionInclude(buildResourcesDir)
}

/**
 * Compute the platform-correct path to `app.asar.unpacked/` inside the
 * built bundle. The previous version of this hook hardcoded
 * `${appOutDir}/resources/...`, which is only correct on Linux/Windows —
 * on macOS the resources sit under `${productFilename}.app/Contents/
 * Resources/...`. As a result, every chmod this hook tried to apply on
 * macOS was pointed at a path that didn't exist, the calls silently
 * no-op'd against a missing tree, and the unpacked binaries shipped with
 * the npm tarball's `0644` mode. `extract.ts` masks the 7za side via a
 * runtime chmod, and `terminal.ts` does the same for spawn-helper, but
 * fixing the pack-time hook means future native helpers don't each need
 * their own runtime workaround.
 *
 * `context.packager.getResourcesDir(appOutDir)` is the electron-builder
 * API that already encodes the per-platform layout — use it instead of
 * re-deriving the path.
 */
function unpackedNodeModulesDir(context) {
  const resourcesDir = context.packager.getResourcesDir(context.appOutDir)
  return path.join(resourcesDir, 'app.asar.unpacked', 'node_modules')
}

/**
 * electron-builder afterPack hook.
 * Ensures bundled native helpers have the execute permission in the packaged
 * output. Without this, the unpacked binaries inherit `0644` from the npm
 * tarball and fail with EACCES at exec time:
 *   - `7za` is invoked when extracting the bundled standalone-python tarball.
 *   - `node-pty/prebuilds/<plat>/spawn-helper` is exec'd by `pty.fork()` to
 *     launch the user's shell. Without +x the Terminal tab and the Settings
 *     Console come up as a black canvas with no prompt — node-pty's native
 *     code fails silently because the exec returns EACCES inside C++ and
 *     the JS layer never sees it.
 * AppImage mounts are read-only, so runtime chmod fails — has to happen at
 * pack time.
 *
 * Switches on `context.electronPlatformName` (the *target* platform) rather
 * than `process.platform` (the *host*), so cross-builds — e.g. ToDesktop's
 * Mac/Linux build VMs producing Windows artifacts — pick the right branch.
 */
export default async function afterPack(context) {
  if (context.electronPlatformName === 'win32') {
    await ensureVcRedist(context)
    return
  }

  const unpackedRoot = unpackedNodeModulesDir(context)
  if (!fs.existsSync(unpackedRoot)) {
    console.log(`afterPack: unpacked node_modules not found at ${unpackedRoot}; skipping chmods`)
    return
  }

  // 7zip-bin / 7za (used during install for the standalone-python tarball).
  const sevenZipRoot = path.join(unpackedRoot, '7zip-bin')
  if (fs.existsSync(sevenZipRoot)) {
    for (const entry of fs.readdirSync(sevenZipRoot, { recursive: true })) {
      if (path.basename(String(entry)) === '7za') {
        const binPath = path.join(sevenZipRoot, String(entry))
        fs.chmodSync(binPath, 0o755)
        console.log(`afterPack: set +x on ${binPath}`)
      }
    }
  }

  // node-pty's prebuilt `spawn-helper` per platform. The native pty.fork
  // exec()s this on every PTY spawn; without +x the helper returns EACCES
  // and the terminal stays black.
  const nodePtyPrebuilds = path.join(unpackedRoot, 'node-pty', 'prebuilds')
  if (fs.existsSync(nodePtyPrebuilds)) {
    for (const entry of fs.readdirSync(nodePtyPrebuilds, { recursive: true })) {
      if (path.basename(String(entry)) === 'spawn-helper') {
        const binPath = path.join(nodePtyPrebuilds, String(entry))
        fs.chmodSync(binPath, 0o755)
        console.log(`afterPack: set +x on ${binPath}`)
      }
    }
  }
}
