!include 'MUI2.nsh'
!include 'FileFunc.nsh'
!include 'LogicLib.nsh'
!include 'WordFunc.nsh'

; Bundled Visual C++ Redistributable versions, generated by
; scripts/afterPack.mjs at build time: VC_REDIST_X64_VERSION and/or
; VC_REDIST_ARM64_VERSION (the FileVersion of the matching
; vc_redist.<arch>.exe, e.g. "14.40.33810.0"), one per Windows
; architecture this build packed.
!include "${BUILD_RESOURCES_DIR}\vc_redist_version.nsh"
; ${IsNativeARM64}: pick the redist for the machine's real architecture.
!include 'x64.nsh'

; electron-builder defines APP_64 / APP_ARM64 for every architecture whose
; payload this installer carries (ToDesktop builds one installer per
; architecture, so exactly one is set). Refuse to compile an installer whose
; redist afterPack never produced: that is how a native ARM64 build would
; silently ship only the x64 runtime, which its win_arm64 Python extension
; modules cannot load.
!ifdef APP_ARM64
  !ifndef VC_REDIST_ARM64_VERSION
    !error "vc_redist.arm64.exe is missing from ${BUILD_RESOURCES_DIR}: scripts/afterPack.mjs did not run for the arm64 target"
  !endif
!endif
!ifdef APP_64
  !ifndef VC_REDIST_X64_VERSION
    !error "vc_redist.x64.exe is missing from ${BUILD_RESOURCES_DIR}: scripts/afterPack.mjs did not run for the x64 target"
  !endif
!endif

; Custom installer artwork (header + welcome/finish sidebars) was wired
; here in #829. It compiles fine for local electron-builder runs but
; fails inside ToDesktop builds at NSIS compile time: ToDesktop's
; BUILD_RESOURCES_DIR is its own build/ dir, NOT electron-builder.yml's
; configured `resources/`, so the BMPs are never present at the path
; the script tries to read. #839's beforeBuild copy-staging attempt
; also failed to take effect (see the 2026-06-04 build log — staging
; log lines never appeared even though platform === 'windows').
;
; Stripped pre-launch so the NSIS step succeeds. electron-builder
; already passes its own MUI_WELCOMEFINISHPAGE_BITMAP /
; MUI_UNWELCOMEFINISHPAGE_BITMAP defaults
; (${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp — visible in the
; build log Command line defines) and we just inherit those. No
; custom header bitmap; the installer uses MUI2's default header strip.
;
; To re-enable custom artwork: figure out the correct ToDesktop-side
; mechanism with ToDesktop support, then restore the four !define
; blocks (the source BMPs are still at resources/installerHeader.bmp,
; resources/installerSidebar.bmp, resources/uninstallerSidebar.bmp).

; Force the install-directory page into the installer flow. electron-builder's
; template (assistedInstaller.nsh) gates `!insertmacro MUI_PAGE_DIRECTORY` on
; `!ifdef allowToChangeInstallationDirectory`. ToDesktop's todesktop.json CLI
; schema rejects the matching `windows.allowToChangeInstallationDirectory`
; key (confirmed by run #27005979459 — same gate that bit the installer-art
; keys in #810/#817), so we set the NSIS define directly here instead — same
; nsisInclude mechanism ToDesktop already accepts. Our sharedHeader is
; prepended ahead of installer.nsi line 40 (`!include "assistedInstaller.nsh"`),
; so this define is in scope before the page macro runs. Guarded with
; !ifndef so if electron-builder/ToDesktop ever set it from above us, we
; won't trip the -WX "macro redefined" failure.
!ifndef allowToChangeInstallationDirectory
  !define allowToChangeInstallationDirectory
!endif

; Friendlier install-mode page strings. electron-builder's defaults read like
; internals ("There is already a per-user installation." / "Will reinstall/
; upgrade."). electron-builder !includes its own message lang file AFTER this
; script, so a *top-level* override here is overridden right back. The
; customHeader hook, however, is inserted AFTER those message includes, so
; re-declaring the LangStrings there wins (NSIS uses the last definition).
; -WX treats the "LangString set multiple times" warning (6030) as an error,
; so suppress just that one. $(^Name) resolves to the product name at runtime.
!macro customHeader
  !pragma warning disable 6030
  ; The install-mode page composes these as "<message>(<install path>)\r\n
  ; <reinstallUpgrade>" (electron-builder's multiUserUi.nsh). The trailing
  ; $\r$\n drops the (path) onto its own line instead of jamming it after the
  ; sentence.
  LangString perUserInstallExists 1033 "$(^Name) is already installed for your account.$\r$\n"
  LangString perUserInstall 1033 "$(^Name) is installed for your account.$\r$\n"
  LangString perMachineInstallExists 1033 "$(^Name) is already installed for all users.$\r$\n"
  LangString perMachineInstall 1033 "$(^Name) is installed for all users.$\r$\n"
  LangString reinstallUpgrade 1033 "Setup will update your existing installation."
  !pragma warning enable 6030

  ; Reveal the install-details list view during install. electron-builder's
  ; common.nsh (included at installer.nsi line 8) defaults to
  ; `ShowInstDetails nevershow`, which hides the standard NSIS Show-Details
  ; button entirely — every DetailPrint line we emit was getting written to
  ; an invisible log. `show` always-displays the list so users watch each
  ; step stream in in real time. Set in customHeader (line 46) so it lands
  ; AFTER common.nsh and overrides the prior value.
  ShowInstDetails show

  ; Pre-install Section that runs the Visual C++ Redistributable BEFORE
  ; electron-builder's main "install" section. The default electron-builder
  ; section order is: files → start-menu shortcut → desktop shortcut →
  ; customInstall (where the redist *used* to run). That ordering let the
  ; user click the freshly-created desktop / Start-menu shortcut and open
  ; the app while VC++ was still installing (#715). Moving the redist into
  ; a hidden Section declared in customHeader places it BEFORE
  ; `Section "install"` (installer.nsi line ~94), so the redist completes
  ; before any shortcut is placed.
  ;
  ; The leading "-" makes the section unselectable / hidden; it has no
  ; component-page entry and always runs. Skipped on update — main install
  ; already-installed check elsewhere; mirrors the prior gate.
  Section "-VcRedistPreInstall"
    ${IfNot} ${isUpdated}
      !insertmacro installVcRedist
    ${EndIf}
  SectionEnd
!macroend

; Optional installer command-line overrides:
;   /ALLUSERS    force a per-machine install
;   /CURRENTUSER force a per-user install
;
; This keeps us on a single ToDesktop Windows build while still allowing
; OEM / IT provisioning flows to request machine installs explicitly.
;
; customInstallMode runs inside the install-mode page's PRE callback. Setting
; $isForceMachineInstall / $isForceCurrentInstall makes that PRE re-apply the
; mode and Abort (skip) the page.
!macro customInstallMode
  ${GetParameters} $R0

  ClearErrors
  ${GetOptions} $R0 "/ALLUSERS" $R1
  ${IfNot} ${Errors}
    StrCpy $isForceMachineInstall 1
  ${Else}
    ClearErrors
    ${GetOptions} $R0 "/CURRENTUSER" $R1
    ${IfNot} ${Errors}
      StrCpy $isForceCurrentInstall 1
    ${Else}
      ; A non-silent update (electron-updater passes --updated but no install-
      ; mode flag) would otherwise stop on the install-mode page — the one
      ; pre-progress page electron-builder does NOT auto-skip on update — making
      ; the user confirm before the progress bar. .onInit's initMultiUser has
      ; already committed a scope into $installMode (matching the lone detected
      ; install, or the per-user default for this perMachine:false app when none
      ; is detected), so on update we force-skip the page using that same scope.
      ; This never switches a cleanly-detected install's scope. (We intentionally
      ; key off $installMode rather than the updater's /D= path: reading /D=
      ; needs electron-builder's GetDParameter macro, which doesn't exist in the
      ; app-builder-lib version ToDesktop builds with.)
      ${If} ${isUpdated}
        ${If} $installMode == "all"
          StrCpy $isForceMachineInstall 1
        ${Else}
          StrCpy $isForceCurrentInstall 1
        ${EndIf}
      ${EndIf}
    ${EndIf}
  ${EndIf}
!macroend

!macro installVcRedist
  # Push/Pop preserves caller registers — defensive in case electron-builder's
  # generated wrapper relies on these across our customInstall hook.
  Push $1
  Push $2
  Push $R6
  Push $R7
  Push $R8
  Push $R9

  # SetDetailsPrint mode for all DetailPrint lines in this macro:
  #   both     = status-bar text AND a line in the Show-Details log
  #
  # electron-builder defaults to `none` (no log lines, no status bar)
  # for interactive installs. We flip to `both` so the user sees what's
  # happening AND can review every step via the "Show Details" button on
  # the install page. We leave it on `both` at the end so subsequent
  # electron-builder operations (file extract, shortcuts, registry,
  # uninstaller write) also appear in the log instead of looking blank.
  SetDetailsPrint both

  # Pick the redistributable for the machine's native architecture. The
  # native ARM64 build (Windows on Arm, e.g. NVIDIA RTX Spark) loads
  # win_arm64 Python extension modules that need the ARM64 runtime; the x64
  # build needs the x64 runtime, also when it runs under Prism emulation on
  # an ARM64 machine. Microsoft's registry contract is per architecture too:
  # https://learn.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files
  #   $R6 = Runtimes\<subkey>   $R7 = bundled version   $R9 = bundled file
  StrCpy $R6 ""
  !ifdef APP_ARM64
    ${If} ${IsNativeARM64}
      StrCpy $R6 "ARM64"
      StrCpy $R7 "${VC_REDIST_ARM64_VERSION}"
      StrCpy $R9 "vc_redist.arm64.exe"
    ${EndIf}
  !endif
  !ifdef APP_64
    ${If} $R6 == ""
      StrCpy $R6 "X64"
      StrCpy $R7 "${VC_REDIST_X64_VERSION}"
      StrCpy $R9 "vc_redist.x64.exe"
    ${EndIf}
  !endif

  ${If} $R6 == ""
    # An ARM64-only installer on a machine that is not native ARM64:
    # electron-builder's own payload selection has nothing to install
    # either, so there is no runtime to provision.
    DetailPrint "Step 1 of 3: Microsoft Visual C++ Redistributable"
    DetailPrint "  No redistributable is bundled for this machine's architecture — skipping."
  ${Else}

  # Discover whether a same-or-newer v14 redist is already installed and skip
  # the multi-minute install in that case. Reads the REG_SZ Version value
  # (form "v14.40.33810.0") of the architecture's key, strips the leading
  # "v", and compares against the bundled version in $R7.
  StrCpy $1 ""
  ClearErrors
  ReadRegStr $1 HKLM "SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\$R6" "Version"
  ${If} ${Errors}
    StrCpy $1 ""
  ${EndIf}

  ${If} $1 != ""
    StrCpy $2 $1 1
    ${If} $2 == "v"
      StrCpy $1 $1 "" 1
    ${EndIf}
  ${EndIf}

  # $2: 0 = equal, 1 = installed > bundled, 2 = installed < bundled or missing.
  # Default to "needs install" if we couldn't read a version.
  ${If} $1 == ""
    StrCpy $2 2
  ${Else}
    ${VersionCompare} "$1" "$R7" $2
  ${EndIf}

  DetailPrint "Step 1 of 3: Microsoft Visual C++ Redistributable ($R6)"
  DetailPrint "  Detected installed version: $1"
  DetailPrint "  Bundled version: $R7"

  ${If} $2 == 2
    DetailPrint "  Installing Microsoft Visual C++ Redistributable (this may take several minutes)..."

    # `File` embeds at compile time, so each architecture's redist is only
    # compiled into an installer that carries that architecture's payload;
    # the runtime pick above extracts exactly one of them.
    !ifdef APP_ARM64
      ${If} $R6 == "ARM64"
        File /oname=$PLUGINSDIR\vc_redist.arm64.exe "${BUILD_RESOURCES_DIR}\vc_redist.arm64.exe"
      ${EndIf}
    !endif
    !ifdef APP_64
      ${If} $R6 == "X64"
        File /oname=$PLUGINSDIR\vc_redist.x64.exe "${BUILD_RESOURCES_DIR}\vc_redist.x64.exe"
      ${EndIf}
    !endif
    # Launch the redist elevated via ShellExecuteEx's "runas" verb (NOT
    # ExecWait/CreateProcess): "runas" with $HWNDPARENT as owner attaches the
    # UAC consent dialog to our window so it foregrounds instead of only
    # flashing in the taskbar. installVcRedist is inserted exactly once, so the
    # labels below cannot collide.
    vcRedistAttempt:
    BringToFront
    ClearErrors
    ExecShellWait "runas" "$PLUGINSDIR\$R9" "/install /quiet /norestart"
    # Capture the error flag into $R8 immediately. ERR = ShellExecuteEx failed
    # to launch/elevate (e.g. the user declined the UAC prompt). A redist that
    # launches and exits with any code (incl. 1638 already-installed / 3010
    # reboot-required) leaves no error.
    StrCpy $R8 "ok"
    ${If} ${Errors}
      StrCpy $R8 "ERR"
    ${EndIf}
    BringToFront

    ${If} $R8 == "ERR"
      DetailPrint "Microsoft Visual C++ Redistributable was not installed (permission prompt declined)."
      BringToFront
      # Abort / Retry / Ignore is the only built-in MessageBox set with an
      # "Abort" button (Windows has no 2-button Retry|Abort).
      #   Retry  -> loop back to vcRedistAttempt (re-show the UAC prompt)
      #   Ignore -> jump past, install without the redist
      #   Abort  -> fall through to Quit (also the silent-install default)
      MessageBox MB_ABORTRETRYIGNORE|MB_ICONEXCLAMATION "Comfy Desktop needs the Microsoft Visual C++ Redistributable. Installing it requires Windows permission, and that prompt was declined.$\n$\nRetry — show the permission prompt again (recommended)$\nIgnore — install ComfyUI anyway (it may not start until the Redistributable is installed)$\nAbort — stop and exit Setup" /SD IDABORT IDRETRY vcRedistAttempt IDIGNORE vcRedistIgnore
      SetErrorLevel 2
      Quit
    ${EndIf}

    DetailPrint "  Microsoft Visual C++ Redistributable installed."
    Goto vcRedistDone
    vcRedistIgnore:
    DetailPrint "  Continuing without the Microsoft Visual C++ Redistributable — ComfyUI may not start until it is installed."
    vcRedistDone:
  ${Else}
    DetailPrint "  Already up to date — skipping install."
  ${EndIf}

  ${EndIf}

  DetailPrint ""
  DetailPrint "Step 2 of 3: Comfy Desktop application files"
  DetailPrint "  Extracting to $INSTDIR (this may take a minute)..."

  Pop $R9
  Pop $R8
  Pop $R7
  Pop $R6
  Pop $2
  Pop $1
!macroend

!macro persistWebsiteAnonymousIdFromInstallerName
  Push $R0
  Push $R1
  Push $R2
  Push $R3
  Push $R4
  Push $R5

  ; GTM-277: the Router serves the signed installer as
  ;   Comfy-Desktop-Setup-phid1_<website PostHog $device_id>.exe
  ; carrying the raw 36-char lowercase UUID. Desktop re-validates the shape
  ; before adopting it.
  ;
  ; Per-machine installs run elevated, possibly as a different account
  ; (over-the-shoulder UAC, SYSTEM), so per-user shell folders resolve to
  ; the wrong profile — skip the carrier entirely.
  ${If} $installMode != "all"
  SetShellVarContext current
  StrCpy $R2 "$APPDATA\Comfy Desktop" ; Electron's packaged userData path
  ; A plain installer must not leave a stale carrier from an earlier unlaunched setup.
  Delete "$R2\pending-website-anonymous-id.txt"

  ${GetFileName} "$EXEPATH" $R0
  StrLen $R5 "$R0"
  StrCpy $R4 ""

  ; 26-char prefix + 36-char UUID = 62. The tail (extension, browser " (1)"
  ; duplicate suffixes) is deliberately ignored — the payload is fixed-length.
  ${If} $R5 >= 62
    StrCpy $R1 "$R0" 26
    ${If} $R1 S== "Comfy-Desktop-Setup-phid1_"
      StrCpy $R4 "$R0" 36 26
    ${EndIf}
  ${EndIf}

  StrLen $R3 "$R4"
  ${If} $R3 == 36
    CreateDirectory "$R2"
    ClearErrors
    FileOpen $R3 "$R2\pending-website-anonymous-id.txt" w
    ${IfNot} ${Errors}
      FileWrite $R3 "$R4$\r$\n"
      FileClose $R3
      DetailPrint "  Website attribution identity stored."
    ${Else}
      DetailPrint "  Website attribution identity could not be stored."
    ${EndIf}
  ${EndIf}
  ${EndIf}

  Pop $R5
  Pop $R4
  Pop $R3
  Pop $R2
  Pop $R1
  Pop $R0
!macroend

!macro customInstall
  ; VC++ Redistributable is now installed by the -VcRedistPreInstall
  ; Section declared in customHeader so it runs BEFORE shortcuts are
  ; placed (#715).
  ;
  ; electron-builder's installSection.nsh sets `SetDetailsPrint none`
  ; at the top of `Section "install"` (line 6), which silences every
  ; line that would otherwise stream through during file extraction,
  ; shortcut creation, registry writes, and uninstaller registration.
  ; By the time customInstall fires those operations have all
  ; completed silently — we flip the mode back to `both` and narrate
  ; them retroactively so the install-details list actually reads
  ; like an install log instead of jumping from "Step 2 — Extracting…"
  ; straight to the Finish page.
  SetDetailsPrint both
  !insertmacro persistWebsiteAnonymousIdFromInstallerName
  DetailPrint "  Application files installed to: $INSTDIR"
  DetailPrint "  Registered with Add or Remove Programs"
  DetailPrint "  Start Menu shortcut created"
  DetailPrint "  Uninstaller written: ${UNINSTALL_FILENAME}"
  DetailPrint ""
  DetailPrint "Step 3 of 3: Finishing up"
  DetailPrint "  Cleaning up temporary files..."
  DetailPrint "  Comfy Desktop is ready to launch."
!macroend

# Custom finish page: launch the app as the current user (not elevated)
!macro customFinishPage
  !ifndef HIDE_RUN_AFTER_FINISH
    Function StartApp
      ${if} ${isUpdated}
        StrCpy $1 "--updated"
      ${else}
        StrCpy $1 ""
      ${endif}
      ${StdUtils.ExecShellAsUser} $0 "$launchLink" "open" "$1"
    FunctionEnd

    !define MUI_FINISHPAGE_RUN
    !define MUI_FINISHPAGE_RUN_FUNCTION "StartApp"
  !endif

  # Opt-out desktop-shortcut checkbox (#682). Pairs with
  # `nsis.createDesktopShortcut: false` in electron-builder.yml so the
  # install section no longer drops a shortcut unconditionally — the user
  # decides on the Finish page. Default is CHECKED so a user clicking
  # straight through still gets a shortcut (no UX regression for the 90%
  # who don't change defaults); only users who actively uncheck skip it.
  #
  # Earlier iteration used the MUI2 `MUI_FINISHPAGE_SHOWREADME=""` +
  # `MUI_FINISHPAGE_SHOWREADME_FUNCTION` trick. Per-MUI2 source that pattern
  # IS valid (checkbox renders, leave handler Calls the function when
  # checked), but field reports came in that the shortcut wasn't being
  # created on Finish even when the box was left checked. Switched to an
  # explicit nsDialogs checkbox wired through MUI_PAGE_CUSTOMFUNCTION_SHOW /
  # _LEAVE so there's no MUI2 magic between the user toggling the box and
  # our shortcut-creation call — easier to reason about + debug.
  #
  # Shortcut creation mirrors what electron-builder's addDesktopLink macro
  # would have done (CreateShortCut → SetLnkAUMI → SHChangeNotify) so the
  # resulting .lnk is identical to the previous always-on path. The
  # `SHCNE_CREATE | SHCNE_UPDATEDIR` notify (0x2 | 0x1000 = 0x1002) tells
  # Explorer to refresh the Desktop folder so the new icon shows up
  # immediately on Finish — the prior `SHCNE_ASSOCCHANGED` (0x8000000) is
  # for file-association changes and is the wrong event for a new shortcut.
  Function CreateUserDesktopShortcut
    CreateShortCut "$newDesktopLink" "$appExe" "" "$appExe" 0 "" "" "${APP_DESCRIPTION}"
    ClearErrors
    WinShell::SetLnkAUMI "$newDesktopLink" "${APP_ID}"
    System::Call 'Shell32::SHChangeNotify(i 0x1002, i 0, i 0, i 0)'
  FunctionEnd

  # Explicit nsDialogs checkbox + leave handler. Position (120u, 110u) +
  # size (195u, 10u) match what MUI2 would have used for its readme
  # checkbox under the Run row, so the layout doesn't visually shift from
  # what users were getting on the old code path.
  Var ComfyDesktopShortcutCheckbox
  Var ComfyDesktopShortcutState

  Function FinishPageShowDesktopShortcutCheckbox
    ${NSD_CreateCheckbox} 120u 110u 195u 10u "Add a desktop shortcut"
    Pop $ComfyDesktopShortcutCheckbox
    ${NSD_SetState} $ComfyDesktopShortcutCheckbox ${BST_CHECKED}
  FunctionEnd

  Function FinishPageLeaveDesktopShortcut
    ${NSD_GetState} $ComfyDesktopShortcutCheckbox $ComfyDesktopShortcutState
    ${If} $ComfyDesktopShortcutState == ${BST_CHECKED}
      Call CreateUserDesktopShortcut
    ${EndIf}
  FunctionEnd

  !define MUI_PAGE_CUSTOMFUNCTION_SHOW FinishPageShowDesktopShortcutCheckbox
  !define MUI_PAGE_CUSTOMFUNCTION_LEAVE FinishPageLeaveDesktopShortcut

  # NOTE: there was a longer effort to enable a working Cancel button +
  # title-bar X on the Finish page (MUI_FINISHPAGE_CANCEL_ENABLED +
  # MUI_CUSTOMFUNCTION_ABORT hooked into MUI2's .onUserAbort,
  # SC_CLOSE re-enabled via EnableMenuItem, nsDialogs ${NSD_OnClick}
  # subclassing as a fallback). None of them routed the click — a
  # diagnostic MessageBox tripwire inside the abort handler never
  # fired, which means nsDialogs swallows the click before NSIS's
  # .onUserAbort sees it, and MUI_CUSTOMFUNCTION_ABORT never runs.
  # The only remaining route is wizard-frame WindowProc subclassing,
  # which is risky and out of scope here. Sticking with Finish-only:
  # the user must click "Finish" to dismiss the wizard.

  !define MUI_PAGE_CUSTOMFUNCTION_PRE FinishPagePreCheck
  !insertmacro MUI_PAGE_FINISH

  # Skip finish page during updates — auto-launch instead. (Updates keep
  # the existing desktop shortcut as-is — electron-builder's keepShortcuts
  # handling is unaffected by createDesktopShortcut: false on update.)
  Function FinishPagePreCheck
    ${if} ${isUpdated}
      ${StdUtils.ExecShellAsUser} $0 "$launchLink" "open" "--updated"
      Abort
    ${endif}
  FunctionEnd
!macroend
